import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  title: "My Next.js App",
  description: "Learning Next.js App Router",
};

export default function RootLayout({
  children,
}: Readonly<{
}: {
  children: React.ReactNode;
}>) {
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      <body className={`${inter.className} flex flex-col min-h-screen text-white`}>
        <div className="fixed inset-0 -z-10">
          <div
            className="w-full h-full bg-cover bg-center bg-no-repeat"
            style={{
              backgroundImage: `url('/images/favbg.jpg  ')`,
            }}
          />
        </div>
        <Header />
        <main className="flex-grow relative z-10 container mx-auto px-4 py-8">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
}
